[LilyGo_Techo-Lite_core]
extends = nrf52_base
board = t-echo-lite
build_flags = ${nrf52_base.build_flags}
  -I variants/techo_Lite
  -D TECHO_LITE
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
build_src_filter = ${nrf52_base.build_src_filter}
  +<helpers/sensors>
  +<../variants/techo_Lite>
lib_deps = ${nrf52_base.lib_deps}

; with e-ink
[LilyGo_Techo-Lite]
extends = LilyGo_Techo-Lite_core
build_flags = ${LilyGo_Techo-Lite_core.build_flags}
  -I src/helpers/ui
  -D DISPLAY_CLASS=SSD1681Display
  -D PIN_USER_BTN=PIN_BUTTON1
build_src_filter = ${LilyGo_Techo-Lite_core.build_src_filter}
  +<helpers/ui/SSD1681Display.cpp>
lib_deps = ${LilyGo_Techo-Lite_core.lib_deps}
  adafruit/Adafruit GFX Library@^1.12.1
  adafruit/Adafruit EPD@^4.5.5
  
[env:LilyGo_T-Echo-Lite_companion_radio_ble]
extends = LilyGo_Techo-Lite
build_flags =
  ${LilyGo_Techo-Lite.build_flags}
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=8
  -D BLE_PIN_CODE=123456
  -D OFFLINE_QUEUE_SIZE=256
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
build_src_filter = ${LilyGo_Techo-Lite.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/companion_radio>
lib_deps =
  ${LilyGo_Techo-Lite.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:LilyGo_T-Echo-Lite-core_companion_radio_ble]
extends = LilyGo_Techo-Lite_core
build_flags =
  ${LilyGo_Techo-Lite_core.build_flags}
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=8
  -D BLE_PIN_CODE=123456
  -D OFFLINE_QUEUE_SIZE=256
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
build_src_filter = ${LilyGo_Techo-Lite_core.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/companion_radio>
lib_deps =
  ${LilyGo_Techo-Lite_core.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:LilyGo_T-Echo-Lite-core_lcd]
extends = LilyGo_Techo-Lite_core
build_flags =
  ${LilyGo_Techo-Lite_core.build_flags}
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=8
  -D BLE_PIN_CODE=123456
  -D OFFLINE_QUEUE_SIZE=256
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
  -D USER_SETUP_LOADED
  -D ST7789_DRIVER
  -D TFT_RGB_ORDER=0
  -D TFT_MISO=-1
  -D TFT_MOSI=47
  -D TFT_SCLK=43
  -D TFT_CS=29
  -D TFT_DC=45
  -D TFT_RST=42
  -D TFT_SPI_PORT=SPI1
  -D TFT_BL=44
  -D TOUCH_CS=-1
  -D LOAD_GLCD=1
  -D LOAD_FONT2
  -D LOAD_GFXFF
  -D SPI_FREQUENCY=16000000
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D DISPLAY_WIDTH=TFT_WIDTH
  -D DISPLAY_HEIGHT=TFT_HEIGHT
  -D TFT_SPI_PORT=SPI1
  -D PIN_SERIAL2_TX=19
  -D PIN_SERIAL2_RX=21
  -D BTN_WAKE=24
  ; -D BLE_DEBUG_LOGGING=1
  ; -D MESH_PACKET_LOGGING=1
  ; -D MESH_DEBUG=1
build_src_filter = ${LilyGo_Techo-Lite_core.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/lcd>
lib_deps =
  ${LilyGo_Techo-Lite_core.lib_deps}
  densaugeo/base64 @ ~1.4.0
  bodmer/TFT_eSPI @ 2.5.43